FROM scratch

MAINTAINER \
[Alexey Shabalin <shaba@altlinux.org>] \
[Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>]

ADD alt-p8-x86_64-20180730.tar.xz /

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["/bin/bash"]
